<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>U03ModemSwitch</AssemblyName>
    <RootNamespace>U03ModemSwitch</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon />
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <VersionPrefix>0.4.0</VersionPrefix>
    <VersionSuffix>dev</VersionSuffix>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Management" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
